#This Dockerfile has been auto-generated by BBC factory, please don't edit manually.

FROM node:8.11

RUN mkdir /s2i

# Copy the S2I scripts to /usr/libexec/s2i since we set the label that way
COPY ./s2i/bin/ /s2i

RUN chmod 777 -R /s2i

LABEL io.openshift.s2i.scripts-url="image:///s2i"